# Generated by Django 4.2.20 on 2025-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesmenu',
            options={'permissions': [{'Can publish dish', 'can_publish_dish'}]},
        ),
    ]
