# Generated by Django 4.2.20 on 2025-06-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsystem', '0002_alter_dishesmenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesmenu',
            options={},
        ),
    ]
